// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CancelOrder(ctx context.Context, id int32) (Order, error)
	// queries/account.sql
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// queries/asset.sql
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	// queries/executed_order.sql
	CreateExecutedOrder(ctx context.Context, arg CreateExecutedOrderParams) (ExecutedOrder, error)
	// queries/order.sql
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	// queries/portfolio.sql
	CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error)
	// queries/transaction.sql
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	// queries/user.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int32) error
	DeleteAsset(ctx context.Context, id int32) error
	DeleteExecutedOrder(ctx context.Context, id int32) error
	DeleteOrder(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetAccount(ctx context.Context, id int32) (Account, error)
	GetAccountByAccountID(ctx context.Context, accountID int64) (Account, error)
	GetAsset(ctx context.Context, id int32) (Asset, error)
	GetAssetBySymbol(ctx context.Context, symbol string) (Asset, error)
	GetExecutedOrder(ctx context.Context, id int32) (ExecutedOrder, error)
	GetOrder(ctx context.Context, id int32) (Order, error)
	GetPortfolio(ctx context.Context, id int32) (Portfolio, error)
	GetPortfolioByAccountID(ctx context.Context, accountID int64) (Portfolio, error)
	GetTotalExecutedQuantity(ctx context.Context, orderID int32) (interface{}, error)
	GetTransaction(ctx context.Context, id []byte) (Transaction, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListAccountsByUserID(ctx context.Context, userID sql.NullInt32) ([]Account, error)
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error)
	ListExecutedOrdersByAccount(ctx context.Context, arg ListExecutedOrdersByAccountParams) ([]ExecutedOrder, error)
	ListExecutedOrdersByOrder(ctx context.Context, arg ListExecutedOrdersByOrderParams) ([]ExecutedOrder, error)
	ListOrdersByAccount(ctx context.Context, arg ListOrdersByAccountParams) ([]Order, error)
	ListPendingOrders(ctx context.Context, arg ListPendingOrdersParams) ([]Order, error)
	ListPortfolioHoldings(ctx context.Context, portfolioID int32) ([]ListPortfolioHoldingsRow, error)
	ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error)
	ListTransactionsByTimeRange(ctx context.Context, arg ListTransactionsByTimeRangeParams) ([]Transaction, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdatePortfolioHolding(ctx context.Context, arg UpdatePortfolioHoldingParams) (PortfolioHolding, error)
	UpdatePortfolioValue(ctx context.Context, arg UpdatePortfolioValueParams) (Portfolio, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
